management:
  endpoints:
    web:
      exposure:
        include: health,prometheus,info,metrics
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true
  prometheus:
    metrics:
      export:
        enabled: true
  metrics:
    tags:
      application: token-engine

spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  flyway:
    locations: classpath:db/migration
  jackson:
    deserialization:
      use-big-decimal-for-floats: true
    serialization:
      write-dates-as-timestamps: false
    time-zone: UTC

token-engine:
  balance-floor: 0
